version: '3.9'

services:
  # web container, with django + gunicorn
  web:
    # Берем Dockerfile из каталога src
    build: ./src
    # Запускаем сервер
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi:application --reload --bind 0.0.0.0:8000
    # volumes:
    #   - static_volume:/home/app/web/staticfiles
    # куда будут помещены данные из каталога app
    # volumes:
    #   - ./src/:/code
    # Подключаем статические и медиа файлы
    volumes:
      - ./src:/home/app/web/
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    # # Открываем порт 8000 внутри и снаружи
    # ports:
    #   - 8000:8000
    # Открываем порт 8000 наружу
    expose:
      - 8000
    depends_on:
        - db
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env

  db:
      image: postgres:13.0-alpine
      # Внешний том (volueme) и место где он будет подключен внутри контейнера
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=django_user
        - POSTGRES_PASSWORD=django_password
        - POSTGRES_DB=django_db

  nginx:
    build: ./src/nginx
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
  

volumes:
  postgres_data:
  static_volume:
  media_volume:

